DROP TABLE MEMBER cascade ;
DROP TABLE ORDERS cascade ;
DROP TABLE DELIVERY cascade ;
DROP TABLE ORDER_ITEM cascade ;
DROP TABLE ITEM cascade ;
DROP TABLE CATEGORY_ITEM cascade ;
DROP TABLE CATEGORY cascade ;

CREATE TABLE MEMBER (
	ID	BIGINT	NOT NULL,
	NAME	VARCHAR(30)	NOT NULL,
	CITY	VARCHAR(30)	NULL,
	STREET	VARCHAR(30)	NULL,
	ZIPCODE	VARCHAR(10)	NULL
);


CREATE TABLE ORDERS (
	ID	BIGINT	NOT NULL,
	MEMBER_ID	BIGINT	NOT NULL,
	DELIVERY_ID	BIGINT	NOT NULL,
	ORDER_DATE	TIMESTAMP	NOT NULL,
	STATUS	INTEGER	NOT NULL
);


CREATE TABLE DELIVERY (
	ID	BIGINT	NOT NULL,
	STATUS	INTEGER	NOT NULL,
	CITY	VARCHAR(30)	NOT NULL,
	STREET	VARCHAR(30)	NOT NULL,
	ZIPCODE	VARCHAR(10)	NOT NULL
);


CREATE TABLE ORDER_ITEM (
	ID	BIGINT	NOT NULL,
	ORDER_ID	BIGINT	NOT NULL,
	ITEM_ID	BIGINT	NOT NULL,
	ORDER_PRICE	INTEGER	NOT NULL,
	COUNT	INTEGER	NOT NULL
);


CREATE TABLE ITEM (
	ID	BIGINT	NOT NULL,
	NAME	VARCHAR(30)	NOT NULL,
	PRICE	INTEGER	NOT NULL,
	STOCK_QUANTITY	INTEGER	NOT NULL,
	DTYPE	VARCHAR(20)	NOT NULL,
	ARTIST	VARCHAR(30)	NULL,
	ETC	VARCHAR(30)	NULL,
	AUTHOR	VARCHAR(30)	NULL,
	ISBN	VARCHAR(30)	NULL,
	DIRECTOR	VARCHAR(30)	NULL,
	ACTOR	VARCHAR(30)	NULL
);

CREATE TABLE CATEGORY (
ID	BIGINT	NOT NULL,
PARENT_CATEGORY_ID	BIGINT	NOT NULL,
NAME	VARCHAR(30)	NOT NULL
);


CREATE TABLE CATEGORY_ITEM (
	ITEM_ID	BIGINT	NOT NULL,
	CATEGORY_ID	BIGINT	NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	ID
);

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (
	ID
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY PRIMARY KEY (
	ID
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (
	ID
);

ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (
	ID
);

ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (
	ID
);

ALTER TABLE CATEGORY_ITEM ADD CONSTRAINT PK_CATEGORY_ITEM PRIMARY KEY (
	ITEM_ID,
	CATEGORY_ID
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_MEMBER_TO_ORDERS_1 FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER (
	ID
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_DELIVERY_TO_ORDERS_1 FOREIGN KEY (
	DELIVERY_ID
)
REFERENCES DELIVERY (
	ID
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ORDERS_TO_ORDER_ITEM_1 FOREIGN KEY (
	ORDER_ID
)
REFERENCES ORDERS (
	ID
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ITEM_TO_ORDER_ITEM_1 FOREIGN KEY (
	ITEM_ID
)
REFERENCES ITEM (
	ID
);

ALTER TABLE CATEGORY ADD CONSTRAINT FK_CATEGORY_TO_CATEGORY_1 FOREIGN KEY (
	PARENT_CATEGORY_ID
)
REFERENCES CATEGORY (
	ID
);

ALTER TABLE CATEGORY_ITEM ADD CONSTRAINT FK_ITEM_TO_CATEGORY_ITEM_1 FOREIGN KEY (
	ITEM_ID
)
REFERENCES ITEM (
	ID
);

ALTER TABLE CATEGORY_ITEM ADD CONSTRAINT FK_CATEGORY_TO_CATEGORY_ITEM_1 FOREIGN KEY (
	CATEGORY_ID
)
REFERENCES CATEGORY (
	ID
);

