DROP TABLE MEMBER cascade ;
DROP TABLE ORDERS cascade ;
DROP TABLE DELIVERY cascade ;
DROP TABLE ORDER_ITEM cascade ;
DROP TABLE ITEM cascade ;

CREATE TABLE MEMBER (
	ID	BIGINT	NOT NULL,
	NAME	VARCHAR(30)	NOT NULL,
	CITY	VARCHAR(30)	NULL,
	STREET	VARCHAR(30)	NULL,
	ZIPCODE	VARCHAR(10)	NULL
);


CREATE TABLE ORDERS (
	ID	BIGINT	NOT NULL,
	MEMBER_ID	BIGINT	NOT NULL,
	DELIVERY_ID	BIGINT	NOT NULL,
	ORDER_DATE	TIMESTAMP	NOT NULL,
	STATUS	INTEGER	NOT NULL
);


CREATE TABLE DELIVERY (
	ID	BIGINT	NOT NULL,
	STATUS	INTEGER	NOT NULL,
	CITY	VARCHAR(30)	NOT NULL,
	STREET	VARCHAR(30)	NOT NULL,
	ZIPCODE	VARCHAR(10)	NOT NULL
);


CREATE TABLE ORDER_ITEM (
	ID	BIGINT	NOT NULL,
	ORDER_ID	BIGINT	NOT NULL,
	ITEM_ID	BIGINT	NOT NULL,
	ORDER_PRICE	INTEGER	NOT NULL,
	COUNT	INTEGER	NOT NULL
);


CREATE TABLE ITEM (
	ID	BIGINT	NOT NULL,
	NAME	VARCHAR(30)	NOT NULL,
	PRICE	INTEGER	NOT NULL,
	STOCK_QUANTITY	INTEGER	NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	ID
);

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY (
	ID
);

ALTER TABLE DELIVERY ADD CONSTRAINT PK_DELIVERY PRIMARY KEY (
	ID
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (
	ID
);

ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (
	ID
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_MEMBER_TO_ORDERS_1 FOREIGN KEY (
	MEMBER_ID
)
REFERENCES MEMBER (
	ID
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_DELIVERY_TO_ORDERS_1 FOREIGN KEY (
	DELIVERY_ID
)
REFERENCES DELIVERY (
	ID
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ORDERS_TO_ORDER_ITEM_1 FOREIGN KEY (
	ORDER_ID
)
REFERENCES ORDERS (
	ID
);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT FK_ITEM_TO_ORDER_ITEM_1 FOREIGN KEY (
	ITEM_ID
)
REFERENCES ITEM (
	ID
);

